from alluvia.distill.scrub import strip_wrappers


def test_strips_local_command_blocks():
    text = ("<local-command-caveat>Caveat: generated by local commands.</local-command-caveat>\n"
            "<command-name>/model</command-name>\n"
            "<command-message>model</command-message>\n"
            "<command-args></command-args>\n"
            "<local-command-stdout>Set model to X</local-command-stdout>\n"
            "real question about caching")
    out = strip_wrappers(text)
    assert "local-command" not in out and "command-name" not in out
    assert "Set model to X" not in out
    assert out.strip() == "real question about caching"


def test_plain_text_untouched():
    assert strip_wrappers("just a normal thought") == "just a normal thought"


def test_distiller_renders_stripped():
    from alluvia.models import Message, RawSession, content_hash, session_id
    from alluvia.llm.client import FakeLLM
    from alluvia.distill.distiller import Distiller
    msgs = [Message(role="user", text="<local-command-caveat>x</local-command-caveat>hello")]
    s = RawSession(id=session_id("claude-code", "s1"), user_id="local",
                   source="claude-code", native_id="s1", title="t",
                   started_at=None, ended_at=None, messages=msgs,
                   content_hash=content_hash(msgs))
    captured = {}

    class Spy(FakeLLM):
        def complete_json(self, system, user):
            captured["user"] = user
            return super().complete_json(system, user)

    Distiller(Spy([{"notes": []}])).distill(s)
    assert "local-command-caveat" not in captured["user"]
    assert "hello" in captured["user"]


def test_claude_code_title_skips_wrapper(tmp_path):
    from alluvia.ingest.claude_code import ClaudeCodeAdapter
    (tmp_path / "s.jsonl").write_text(
        '{"type":"user","message":{"role":"user","content":'
        '"<local-command-caveat>noise</local-command-caveat>the actual topic"}}\n')
    s = list(ClaudeCodeAdapter(str(tmp_path)).read())[0]
    assert s.title.startswith("the actual topic")
